spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weather_diary?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  config:
    import: secret.yml

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  config: classpath:logback-spring.xml